#cloud-config
---

#This YAML file is a cloud-init configuration file used to bootstrap nodes in the environment.
#This file is used to bootstrap configure the First Master Node in the First Cluster.

#Redirect all output to the log file
output: {all: '| tee -a /var/log/cloud-init-output.log'}

#Set System config
manage_etc_hosts: true
manage_resolv_conf: true

#Set Hostname and fqdn
fqdn: kube-demo-mgmt-wn02.kube-demo.lab
hostname: kube-demo-mgmt-wn02

#Set Packages Update Configurations
package_update: true
package_upgrade: true
package_reboot_if_required: true

#Write data to the required config files
write_files:
  - path: "/etc/cloud/templates/hosts.debian.tmpl"
    content: |
      127.0.0.1   localhost localhost.localdomain localhost4 localhost4.localdomain4
      ::1         localhost6 localhost6.localdomain6
      10.10.11.100 kube-demo-mgmt-mn01
      10.10.11.101 kube-demo-mgmt-wn01
      10.10.11.102 kube-demo-mgmt-wn02
